# Site settings
title: David的博客
email: zhangdavidzh@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  David的博客
baseurl: "" # the subpath of your site, e.g. /blog/
url: http://.org # the base hostname & protocol for your site
rss_url: /pages/feed.xml
author: David

# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'category'
recent_num: 20

# Social account
twitter: tbd
weibo: tbd
github: tbd
instagram: tbd
linkedin: tbd

# avatar and Favicon
avatar: tbd #http://7u2ho6.com1.z0.glb.clouddn.com/site-avatar.png
favicon: tbd #http://7u2ho6.com1.z0.glb.clouddn.com/site-favicon.ico

# disqus config
disqus:
  shortname: DZ

# google analytics config
ga:
  id: UA-54767140-1
  url: tbd #yansu.org

# Build settings
permalink: /:year/:month/:day/:title.html
markdown: kramdown
highlighter: rouge
mathjax: disabled
sass:
  style: compressed

# Jekyll Plugin
# https://help.github.com/articles/adding-jekyll-plugins-to-a-github-pages-site/
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

